"""empty message

Revision ID: 473bddc76c81
Revises: 978d90d1b40d
Create Date: 2022-08-19 11:06:35.298781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '473bddc76c81'
down_revision = '978d90d1b40d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Artist_genres')
    op.drop_table('Venue_genres')
    op.add_column('Artist', sa.Column('genres', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('genres', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genres')
    op.drop_column('Artist', 'genres')
    op.create_table('Venue_genres',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Venue_genres_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('genre', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], name='Venue_genres_venue_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Venue_genres_pkey')
    )
    op.create_table('Artist_genres',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Artist_genres_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('genre', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], name='Artist_genres_artist_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Artist_genres_pkey')
    )
    # ### end Alembic commands ###
