"""empty message

Revision ID: 850dc410cc0d
Revises: ff666a6e949a
Create Date: 2022-08-16 12:36:30.992636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '850dc410cc0d'
down_revision = 'ff666a6e949a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Venue_genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genre', sa.String(length=120), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('t1')
    op.add_column('Venue', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('Venue', sa.Column('seeking_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'seeking_description')
    op.drop_column('Venue', 'seeking_talent')
    op.drop_column('Venue', 'website_link')
    op.create_table('t1',
    sa.Column('c1', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('c2', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('c1', name='t1_pkey')
    )
    op.drop_table('Venue_genres')
    # ### end Alembic commands ###
